version: "3"
services:
  f4:
    build: .
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - config:/home/f4/.eclipse:rw
      - ${WORKSPACE}:/home/f4/f4workspace:rw
      - ${INTERPRETERS}:/home/f4/interpreters:rw

volumes:
  config:
